### ISSUE TITLE
** (File.Error) could not read file "lib/stationary/feed.rss.eex": no such file or directory

### ISSUE THREAD

**Issue by richardrissanen** [jarrodtaylor/stationary#19]
Following the readme produces an error when running `mix stationary.build`

    ** (File.Error) could not read file "lib/stationary/feed.rss.eex": no such file or directory
        (elixir) lib/file.ex:244: File.read!/1
        lib/eex.ex:181: EEx.compile_file/2
        lib/eex.ex:216: EEx.eval_file/3
        lib/stationary/builder.ex:64: Stationary.Builder.do_build/1
        (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
        (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

**Comment by richardrissanen** [comment]
This is what I needed.

    defp deps do
        [{:stationary, git: "https://github.com/jarrodtaylor/stationary.git"}]
    end
